export default {
    /* Header message websocket */
    TAG_TOKEN :      "token",
    TAG_MSG_ID :     "message_id",
    TAG_MSG_TYPE :   "message_type",
    TAG_MSG_ACTION:  "message_action",
    TAG_SEQ_NO :     "sequence_no",
    TAG_NUMBER_PART : "number_part",
    TAG_CONT_SIZE :  "content_size",
    TAG_CONTENT :    "content",

    /* tag property of pdf file */
    TAG_ID:       "id",
    TAG_NAME:       "name",
    TAG_TOTAL_PAGE:       "totalPage",
    TAG_NUMBER_OK_PAGE:       "okPage",
    TAG_NUMBER_MANUAL_PAGE:       "manualPage",
    TAG_NUMBER_NG_PAGE:       "ngPage",
    TAG_NUMBER_NO_NUMBERING_PAGE:      "numberNoNumbering",
    TAG_BEGIN_SERIAL:       "beginSerial",
    TAG_END_SERIAL:       "endSerial",
    TAG_PROCESS_STATUS:       "processStatus",
    TAG_SOURCE_UPLOAD:       "sourceUpload",
    TAG_UPLOADED_DATE:       "uploadedDate",
    TAG_UPDATED_DATE:       "updatedDate",
    TAG_LIST_PAGE:       "listPage",

    TAG_BEGIN_UPLOADED_DATE:       "beginUploadedDate",
    TAG_END_UPLOADED_DATE:       "endUploadedDate",
    TAG_PDF_FILES:  "pdfFiles",
    TAG_LIST_DOCTOR:    "listDoctor",
    TAG_NO_DOCTOR_INFO:   "noDoctorInfo",
    TAG_FILE_NOT_YET_CHECKED: "notYetChecked",

    /* tag property of pdf page */
    TAG_PAGE:            "page",
    TAG_PAGE_INDEX:       "pageIndex",
    TAG_SERIAL:            "serial",
    TAG_FORM_TYPE:       "formType",
    TAG_COMPANY:       "company",
    TAG_INSURANCE_NO:       "no",
    TAG_DETECTED_RESULT:       "detectedResult",
    TAG_SIGN_RESULT:       "signResult",
    TAG_DOCTER_SEAL_RESULT:       "docterSealResult",
    TAG_ID_NO_RESULT:       "idNoResult",
    TAG_ADDRESS_RESULT:       "addressResult",
    TAG_ORDER_DATE_RESULT:       "orderDateResult",
    TAG_REASON_RESULT:       "reasonResult",
    TAG_BIRTHDAY_RESULT:       "birthdayResult",
    TAG_RELATIONSHIP_RESULT:       "relationshipResult",
    TAG_COMMENT_RESULT:       "commentResult",
    TAG_GENDER_RESULT:       "genderResult",
    TAG_BUCKET_NO:       "bucketNo",
    TAG_INSURANCE_NO_RESULT:    "insuranceNoResult",
    TAG_NUMBERING_RESULT:   "numberingResult",
    TAG_RESULT:      "Result",

    TAG_RAW_DATA:    "rawData",
    TAG_ADDRESS:    "address",
    TAG_NAME_PATIENT: "namePatient",
    TAG_NAME_OWNER: "nameOwner",
    TAG_AGE: "age",
    TAG_RELATIONSHIP: "relationShip",
    TAG_GENDER: "gender",
    TAG_INJURY:      "injury",
    TAG_SPECIALCHAR: "specialChar",
    TAG_DOCTOR_NAME: "doctorName",
    TAG_DOCTOR_ID: "doctorId",
    TAG_COST:   "cost",
    TAG_CHANGE_INFOS:   "changeInfos",
    TAG_STATUS_CONFIRM:  "statusConfirm",

    /* tag property of setting doctor */
    TAG_IMAGES:  "images",
    TAG_IMAGE_ERROR: "imageError",

    /* tag property of setting user */
    TAG_USERNAME: "username",
    TAG_PASSWORD: "password",
    TAG_GROUP: "group",
    TAG_DESCRIPTION: "Description",
    TAG_USERS: "users",

    /* Common tag key */
    TAG_TOTAL : "total",
    TAG_INDEX :  "index",
    TAG_COUNT :  "count",
    TAG_NUMBER :  "number",
    TAG_ERROR_CODE : "errorCode",
    TAG_IMAGE :      "image",
    TAG_SIZE:    "size",
    TAG_TEXT:    "text",
    TAG_VALUE:   "value",
    TAG_STATUS_TYPE: "statusType",
    TAG_DETECTED_RESULT_MODE: "detectedResultMode",
    TAG_SELECT_ALL: "selectAll",
    TAG_STEP_NO: "stepNo",
    TAG_MODE_DATA: "modeData",
    TAG_STEP_RESULT: "stepResult",
    TAG_USER: "user",

    /* tag property of usb data */
    TAG_USB_DATA_FILE:    "usbDataFile",
    TAG_BILLING_DATE:    "billingDate",
    TAG_TOTAL_MONEY_SCANNED_FORM:    "totalMoneyOfScannedForm",
    TAG_TOTAL_MONEY_UNSCANNED_FORM:  "totalMoneyOfUnScannedForm",
    TAG_TOTAL_MONEY:     "totalMoney",
    TAG_FILE_TYPE:       "fileType",
    TAG_FILE_NAME:      "fileName",
    /* tag property of csv data */
    TAG_CSV_DATA_FILE:  "csvDataFile",
    TAG_CSV_DATA_FILES: "csvDataFiles",
    TAG_MONTH_INFO: "monthInfo",
    TAG_LIST_CSV_DATA_FILE: "listCsvDataFile",
    TAG_LIST_CHECK_COST_RESULT: "listCheckCostResult",
    TAG_LIST_CHECK_COST_OF_PAGE_RESULT:   "listCheckCostOfPageResult",
    TAG_ID_PDFFILE: "idPDFFile",
    TAG_RESULT_CONFIRM: "resultConfirm",
    TAG_ID_CSVDATAFILE: "idCSVDataFile",
    TAG_TOTAL_FILE: "totalFile",
    TAG_ROW_INDEX: "rowIndex",
    TAG_CONFIRMED:  "confirmed",
    TAG_ID_CONFIRMED_DATETIME:  "confirmedDateTime",
    TAG_TOTAL_RESULT:  "totalResult",
    TAG_NUMBER_OK_RESULT:  "okResult",
    TAG_NUMBER_MANUAL_RESULT:  "manualResult",
    TAG_NUMBER_NG_RESULT:  "ngResult",
    TAG_NUMBER_PAGE: "numberPage",
    TAG_NUMBER_ROW: "numberRow",
    TAG_NUMBER_PAGE_NG: "numberPageNG",
    TAG_NUMBER_ROW_NG: "numberRowNG",
    TAG_PDF_SERIAL: "pdfSerial",
    TAG_PDF_INSURANCE_NO:   "pdfInsuranceNo",
    TAG_PDF_NAME_OWNER: "pdfNameOwner",
    TAG_PDF_COST:   "pdfCost",
    TAG_CSV_BILLING_DATE:   "csvBillingDate",
    TAG_CSV_NAME_OWNER: "csvNameOwner",
    TAG_CSV_INSURANCE_NO:   "csvInsuranceNo",
    TAG_CSV_COST:   "csvCost",
    TAG_CSV_RECORD_DATA:    "csvRecordData",

    /*tag image of step*/
    TAG_STEP_1_IMAGE: "step1Image",
    TAG_STEP_2_IMAGE: "step2Image",
    TAG_STEP_3_IMAGE: "step3Image",
    TAG_STEP_4_IMAGE: "step4Image",
    TAG_STEP_5_IMAGE: "step5Image",
    TAG_STEP_6_IMAGE: "step6Image",
    TAG_STEP_7_IMAGE: "step7Image",
    TAG_STEP_8_IMAGE: "step8Image",
    TAG_STEP_9_IMAGE: "step9Image",
    TAG_STEP_10_IMAGE: "step10Image",

    /* config tag key */
    TAG_CONFIG_TYPE: "configType"
}
